services:
  crops-yocto:
    image: crops/yocto:ubuntu-22.04-base
    command: sleep infinity
    volumes:
      # Mount working dir
      - .:/workspaces/simplest-yocto-setup
      # Mount shared caches dir
      - ${HOME}/yocto-caches:/workspaces/simplest-yocto-setup/caches
      # Mount SSH credentials for git access
      - ${HOME}/.ssh:/home/yoctouser/.ssh:ro
      # Mount shell history files
      - ${HOME}/.zsh_history:/home/yoctouser/.zsh_history
      - ${HOME}/.bash_history:/home/yoctouser/.bash_history
