# Machine configuration for the Dogbone Darker product.
#
# This is a fictitious product, identical to the Dogbone Dark
# (Beaglebone Black) but configured to use out-of-source kernel and
# U-Boot defconfigs and device trees shipped from this layer.

require include/common.inc

# Adds "ti-soc" and "ti33x" to MACHINEOVERRIDES, and ultimately to
# OVERRIDES
require conf/machine/include/soc-family.inc
SOC_FAMILY = "ti-soc:ti33x"

# Defines instruction sets and tunes for the CPU in the SoC
require conf/machine/include/arm/armv7a/tune-cortexa8.inc
DEFAULTTUNE = "armv7athf-neon"

# Basic info about the hardware
MACHINE_FEATURES = "apm usbgadget usbhost alsa"
SERIAL_CONSOLES = "115200;ttyS0"

# Select kernel recipe, set parameters for kernel build. The device
# tree is shipped by meta-kiss (see linux-kiss.inc) and copied into
# the kernel source tree at do_configure time.
PREFERRED_PROVIDER_virtual/kernel ?= "linux-kiss"
KERNEL_DEVICETREE = "ti/omap/am335x-dogbonedarker.dtb"
KERNEL_IMAGETYPE = "zImage"

# Select bootloader recipe, set parameters for bootloader build. The
# defconfig and device tree are shipped by meta-kiss (see
# u-boot-kiss_git.bb) and dropped into the U-Boot tree at
# do_configure time.
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-kiss"
UBOOT_ARCH = "arm"
UBOOT_MACHINE = "dogbonedarker_defconfig"
UBOOT_MAKE_TARGET = " DEVICE_TREE=am335x-dogbonedarker"
UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_LOADADDRESS = "0x80008000"
UBOOT_BINARY = "u-boot.img"
SPL_BINARY = "MLO"

# We need MLO and u-boot.img in /boot (wic will copy them to the FAT
# partition). Expanding PREFERRED_PROVIDER_virtual/bootloader instead of
# writing u-boot-kiss allows this line to work even in case the bootloader
# is overridden, e.g. via local.conf.
IMAGE_INSTALL:append = " ${PREFERRED_PROVIDER_virtual/bootloader}"
